from typing import Dict
from jinja2 import Template
import os


class ReportGenerator:
    """
    Generates HTML reports from backtest metrics and history.
    """

    TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Backtest Report - {{ strategy_name }}</title>
    <style>
        body { font-family: sans-serif; margin: 40px; background: #f4f7f6; }
        .container { max-width: 1000px; margin: auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #333; }
        .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 20px 0; }
        .metric-card { background: #fff; border: 1px solid #ddd; padding: 15px; border-radius: 6px; text-align: center; }
        .metric-value { font-size: 24px; font-weight: bold; color: #2c3e50; }
        .metric-label { font-size: 14px; color: #7f8c8d; margin-top: 5px; }
        .positive { color: #27ae60; }
        .negative { color: #e74c3c; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { text-align: left; padding: 12px; border-bottom: 1px solid #eee; }
        th { background: #f8f9fa; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Backtest Report: {{ strategy_name }}</h1>
        <p>Symbol: {{ symbol }} | Timeframe: {{ timeframe }}</p>
        
        <div class="summary-grid">
            <div class="metric-card">
                <div class="metric-value {% if metrics.total_return > 0 %}positive{% elif metrics.total_return < 0 %}negative{% endif %}">
                    {{ (metrics.total_return * 100) | round(2) }}%
                </div>
                <div class="metric-label">Total Return</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{{ (metrics.max_drawdown * 100) | round(2) }}%</div>
                <div class="metric-label">Max Drawdown</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{{ metrics.sharpe_ratio | round(2) }}</div>
                <div class="metric-label">Sharpe Ratio</div>
            </div>
        </div>

        <h2>Details</h2>
        <table>
            <tr><th>Initial Capital</th><td>{{ initial_capital }}</td></tr>
            <tr><th>Final Equity</th><td>{{ metrics.final_equity | round(2) }}</td></tr>
            <tr><th>Peak Equity</th><td>{{ metrics.peak_equity | round(2) }}</td></tr>
            <tr><th>Volatility (Daily/Period)</th><td>{{ metrics.volatility | round(4) }}</td></tr>
        </table>
        
        <p style="margin-top: 40px; color: #999; font-size: 12px;">Generated by Trading Backtest Engine</p>
    </div>
</body>
</html>
    """

    @staticmethod
    def generate(
        metrics: Dict,
        strategy_name: str,
        symbol: str,
        timeframe: str,
        initial_capital: float,
        output_path: str = "report.html",
    ):
        template = Template(ReportGenerator.TEMPLATE)
        html_content = template.render(
            metrics=metrics,
            strategy_name=strategy_name,
            symbol=symbol,
            timeframe=timeframe,
            initial_capital=initial_capital,
        )

        with open(output_path, "w") as f:
            f.write(html_content)

        return os.path.abspath(output_path)
